# Generated by Django 3.1.2 on 2020-10-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('profession_name', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name_plural': 'professional type',
            },
        ),
    ]
