# Generated by Django 3.1.2 on 2020-10-22 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Job type',
            },
        ),
        migrations.RemoveField(
            model_name='professionaltype',
            name='profession_name',
        ),
        migrations.AddField(
            model_name='professionaltype',
            name='created_on',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
