# Generated by Django 3.1.2 on 2020-10-23 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20201023_1025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='updated_on',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='useraddress',
            old_name='created_on',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='jobs',
            name='publish_end_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.CharField(max_length=30, null=True)),
                ('year_from', models.CharField(max_length=30, null=True)),
                ('year_to', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_o', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user Eduction',
            },
        ),
    ]
