# Generated by Django 3.1.2 on 2020-10-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201023_1122'),
        ('core', '0007_auto_20201023_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.RemoveField(
            model_name='experiences',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProfessionalType',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='useroverview',
            name='user',
        ),
        migrations.AlterField(
            model_name='jobs',
            name='skills_needed',
            field=models.ManyToManyField(to='authentication.UserSkills'),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Experiences',
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Suggestion',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
        migrations.DeleteModel(
            name='UserOverview',
        ),
    ]
