# Generated by Django 3.1.2 on 2020-10-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201022_1344'),
        ('authentication', '0002_auto_20201022_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='enable_authenticator',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='price_per_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='profession_type',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professionaltype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, choices=[('S', 'Software developer'), ('D', 'Web designer'), ('G', 'Graphic Designe')], max_length=20, null=True),
        ),
    ]
