# Generated by Django 3.1.2 on 2020-10-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_experiences'),
        ('authentication', '0005_auto_20201022_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experiences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='core.Skills'),
        ),
    ]
