# Generated by Django 3.1.2 on 2020-10-23 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20201023_1122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usereducation',
            options={'verbose_name_plural': 'User Education'},
        ),
        migrations.AlterModelOptions(
            name='useroverview',
            options={'verbose_name_plural': 'User description'},
        ),
        migrations.AlterModelOptions(
            name='userprofessionaltype',
            options={'verbose_name_plural': 'User professional type'},
        ),
        migrations.AlterModelOptions(
            name='usersuggestions',
            options={'verbose_name_plural': 'User Suggestions'},
        ),
        migrations.CreateModel(
            name='UserPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_link', models.URLField(blank=True, null=True, unique=True)),
                ('web_link', models.URLField(blank=True, null=True, unique=True)),
                ('cover_picture', models.ImageField(upload_to='portfolio_images')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_o', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User portfolio',
            },
        ),
    ]
