# Generated by Django 3.1.2 on 2020-10-24 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20201023_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password2',
            field=models.CharField(editable=False, max_length=40, null=True),
        ),
    ]
