# Generated by Django 3.1.2 on 2020-11-07 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20201107_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profession',
        ),
    ]
