# Generated by Django 3.1.2 on 2020-11-07 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20201107_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Follow and following'},
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='following',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_pc',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_pc',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to='profile_pic'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user_id', 'follower'), name='unique_followers'),
        ),
    ]
