# Generated by Django 3.1.2 on 2020-11-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_auto_20201107_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pc',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='profile_pic'),
        ),
    ]
