# Generated by Django 3.1.2 on 2020-11-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_auto_20201107_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_pc',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pc',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='ProfilePics'),
        ),
    ]
