# Generated by Django 3.1.2 on 2020-11-09 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=30, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=30, null=True)),
                ('password1', models.CharField(max_length=40, null=True)),
                ('password2', models.CharField(blank=True, max_length=20, null=True)),
                ('agreed_to_terms', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'company',
            },
        ),
    ]
