# Generated by Django 3.1.2 on 2020-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password2',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True),
        ),
    ]
